package com.cloudshare.scheduler;

import com.cloudshare.model.FileMetadata;
import com.cloudshare.repository.FileRepository;
import com.cloudshare.repository.UserRepository;
import com.cloudshare.model.User;
import com.cloudshare.model.AuditLog;
import com.cloudshare.service.AuditLogService;
import com.cloudshare.service.StorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.data.redis.core.StringRedisTemplate;
import com.cloudshare.service.ClamAvService;

import java.io.ByteArrayInputStream;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Collections;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(properties = {
    "storage.provider=LOCAL",
    "storage.local.directory=target/test-uploads"
})
@ActiveProfiles("test")
class SchedulerIntegrationTest {

    @Autowired
    private FilePurgeScheduler filePurgeScheduler;

    @Autowired
    private LinkCleanupScheduler linkCleanupScheduler;

    @Autowired
    private FileRepository fileRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private com.cloudshare.repository.ShareLinkRepository shareLinkRepository;

    @Autowired
    private StorageService storageService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private AuditLogService auditLogService;

    @MockitoBean(name = "redisTemplate")
    private StringRedisTemplate redisTemplate;

    @MockitoBean(name = "securityRedisTemplate")
    private StringRedisTemplate securityRedisTemplate;

    @MockitoBean
    private ClamAvService clamAvService;

    private User testUser;

    @BeforeEach
    void setUp() {
        // Create audit_logs table dynamically in H2 as it's not a JPA Entity
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS audit_logs (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id UUID, " +
                "action VARCHAR(50) NOT NULL, " +
                "file_id UUID, " +
                "ip_address VARCHAR(45) NOT NULL, " +
                "details TEXT, " +
                "created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL" +
                ")");

        // Clear tables
        jdbcTemplate.execute("DELETE FROM audit_logs");
        jdbcTemplate.execute("DELETE FROM share_links");
        jdbcTemplate.execute("DELETE FROM file_shares");
        jdbcTemplate.execute("DELETE FROM files");
        jdbcTemplate.execute("DELETE FROM user_roles");
        jdbcTemplate.execute("DELETE FROM users");

        // Create a test user
        testUser = User.builder()
                .username("test_user_purge")
                .email("test_user_purge@example.com")
                .passwordHash("password")
                .mfaEnabled(false)
                .roles(Collections.emptySet())
                .build();
        testUser = userRepository.save(testUser);
    }

    @Test
    void testFilePurgeScheduler_purgesOldSoftDeletedFiles() throws Exception {
        // 1. Create a file that is active (not soft deleted)
        FileMetadata activeFile = FileMetadata.builder()
                .ownerId(testUser.getId())
                .storagePath("active-file-path")
                .originalFilename("active.txt")
                .fileSizeBytes(100L)
                .mimeType("text/plain")
                .checksumSha256("sha256")
                .encryptedFek("fek")
                .ivGcm("iv")
                .kekVersion(1)
                .deleted(false)
                .build();
        activeFile = fileRepository.save(activeFile);
        storageService.store(activeFile.getStoragePath(), new ByteArrayInputStream("active content".getBytes()));

        // 2. Create a file that is soft-deleted recently (less than 30 days ago)
        FileMetadata recentlyDeletedFile = FileMetadata.builder()
                .ownerId(testUser.getId())
                .storagePath("recent-deleted-file-path")
                .originalFilename("recent.txt")
                .fileSizeBytes(100L)
                .mimeType("text/plain")
                .checksumSha256("sha256")
                .encryptedFek("fek")
                .ivGcm("iv")
                .kekVersion(1)
                .deleted(true)
                .build();
        recentlyDeletedFile = fileRepository.save(recentlyDeletedFile);
        storageService.store(recentlyDeletedFile.getStoragePath(), new ByteArrayInputStream("recent content".getBytes()));

        // 3. Create a file that is soft-deleted 31 days ago
        FileMetadata oldDeletedFile = FileMetadata.builder()
                .ownerId(testUser.getId())
                .storagePath("old-deleted-file-path")
                .originalFilename("old.txt")
                .fileSizeBytes(100L)
                .mimeType("text/plain")
                .checksumSha256("sha256")
                .encryptedFek("fek")
                .ivGcm("iv")
                .kekVersion(1)
                .deleted(true)
                .build();
        oldDeletedFile = fileRepository.save(oldDeletedFile);
        storageService.store(oldDeletedFile.getStoragePath(), new ByteArrayInputStream("old content".getBytes()));

        // Manually update updated_at in the database to be 31 days ago (bypassing JPA PreUpdate)
        jdbcTemplate.update("UPDATE files SET updated_at = ? WHERE id = ?",
                Timestamp.from(Instant.now().minus(31, ChronoUnit.DAYS)),
                oldDeletedFile.getId());

        // 4. Trigger the scheduler
        filePurgeScheduler.purgeFiles();

        // 5. Verification
        // - Active file should still exist in DB and storage
        assertTrue(fileRepository.findById(activeFile.getId()).isPresent());
        assertNotNull(storageService.retrieve(activeFile.getStoragePath()));

        // - Recently deleted file should still exist in DB and storage (since it's < 30 days old)
        assertTrue(fileRepository.findById(recentlyDeletedFile.getId()).isPresent());
        assertNotNull(storageService.retrieve(recentlyDeletedFile.getStoragePath()));

        // - Old deleted file should be purged from DB
        assertFalse(fileRepository.findById(oldDeletedFile.getId()).isPresent());
        
        // - Old deleted file should be purged from storage (storageService.retrieve should fail)
        final String oldStoragePath = oldDeletedFile.getStoragePath();
        assertThrows(Exception.class, () -> storageService.retrieve(oldStoragePath));

        // - Verify audit log entry exists for the purged file
        List<AuditLog> auditLogs = auditLogService.getAuditLogs(null, "FILE_PURGE", org.springframework.data.domain.PageRequest.of(0, 10)).getContent();
        assertEquals(1, auditLogs.size());
        assertEquals("FILE_PURGE", auditLogs.get(0).getAction());
        assertEquals(oldDeletedFile.getId(), auditLogs.get(0).getFileId());
    }

    @Test
    void testLinkCleanupScheduler_purgesExpiredLinks() throws Exception {
        // Create an active file first
        FileMetadata file = FileMetadata.builder()
                .ownerId(testUser.getId())
                .storagePath("link-file-path")
                .originalFilename("link.txt")
                .fileSizeBytes(100L)
                .mimeType("text/plain")
                .checksumSha256("sha256")
                .encryptedFek("fek")
                .ivGcm("iv")
                .kekVersion(1)
                .deleted(false)
                .build();
        file = fileRepository.save(file);

        // 1. Create a share link that is not expired
        com.cloudshare.model.ShareLink activeLink = com.cloudshare.model.ShareLink.builder()
                .file(file)
                .shareCode("activecode123")
                .expiresAt(Instant.now().plus(1, ChronoUnit.HOURS))
                .downloadLimit(10)
                .downloadCount(0)
                .build();
        activeLink = shareLinkRepository.save(activeLink);

        // 2. Create a share link that is expired
        com.cloudshare.model.ShareLink expiredLink = com.cloudshare.model.ShareLink.builder()
                .file(file)
                .shareCode("expiredcode123")
                .expiresAt(Instant.now().minus(1, ChronoUnit.HOURS))
                .downloadLimit(10)
                .downloadCount(0)
                .build();
        expiredLink = shareLinkRepository.save(expiredLink);

        // 3. Trigger the link cleanup scheduler
        linkCleanupScheduler.cleanupLinks();

        // 4. Verification
        // - Active link should still exist
        assertTrue(shareLinkRepository.findById(activeLink.getId()).isPresent());

        // - Expired link should be deleted
        assertFalse(shareLinkRepository.findById(expiredLink.getId()).isPresent());

        // - Verify audit log entry exists for the purged link (a single summary log)
        List<AuditLog> auditLogs = auditLogService.getAuditLogs(null, "LINK_CLEANUP", org.springframework.data.domain.PageRequest.of(0, 10)).getContent();
        assertEquals(1, auditLogs.size());
        assertEquals("LINK_CLEANUP", auditLogs.get(0).getAction());
        assertNull(auditLogs.get(0).getFileId());
        assertTrue(auditLogs.get(0).getDetails().contains("Bulk purged 1 expired share links"));
    }

    @Test
    void testH2SkipLockedCompatibility() {
        FileMetadata file = FileMetadata.builder()
                .ownerId(testUser.getId())
                .storagePath("h2-test-lock-path")
                .originalFilename("test-lock.txt")
                .fileSizeBytes(100L)
                .mimeType("text/plain")
                .checksumSha256("sha256")
                .encryptedFek("fek")
                .ivGcm("iv")
                .kekVersion(1)
                .deleted(false)
                .build();
        file = fileRepository.save(file);

        List<FileMetadata> batch = fileRepository.findBatchForReKey(1, java.util.Collections.singletonList(java.util.UUID.randomUUID()), 10);
        assertNotNull(batch);
        assertEquals(1, batch.size());
        assertEquals(file.getId(), batch.get(0).getId());
    }
}
