apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudshare.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudshare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
