{{- if .Values.serviceMonitor.enabled }}
# Требует CRD ServiceMonitor (prometheus-operator, ставится в фазе 6)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudshare.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudshare.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
